using System.Collections;
using UnityEngine;

/// <summary>
/// Class that is in charge of resetting the parameters of the bullets generated by pooling.
/// </summary>
public class Bullet : MonoBehaviour
{
    [SerializeField] AudioSource shootSound = null;
    [SerializeField] TrailRenderer trailRenderer = null;
    [SerializeField] Rigidbody rb = null;

    void OnEnable()
    {
        shootSound.Play();
        trailRenderer.Clear();
        StartCoroutine(DestroyBullet());
    }

    private void OnDisable()
    {
        rb.velocity = Vector3.zero;
        StopAllCoroutines();
    }

    /// <summary>
    /// Coroutine in charge of destroying the bullets after a few seconds.
    /// </summary>
    /// <returns></returns>
    IEnumerator DestroyBullet()
    {
        yield return new WaitForSeconds(2);

        gameObject.SetActive(false);
    }
}
